const questions = [
  // --- หมวดที่ 1: ความสามารถทั่วไป (คณิตศาสตร์) [30 ข้อ: 1-30] ---
  { "id": 1, "category": "คณิตศาสตร์", "question": "อนุกรม: 2, 6, 12, 20, 30, ... ตัวเลขถัดไปคือข้อใด?", "options": ["40", "42", "44", "46"], "answerIndex": 1, "explanation": "เพิ่มขึ้นทีละเลขคู่: +4, +6, +8, +10 ถัดไปคือ +12 (30+12 = 42)" },
  { "id": 2, "category": "คณิตศาสตร์", "question": "อนุกรม: 3, 9, 27, 81, ... ตัวเลขถัดไปคือข้อใด?", "options": ["162", "243", "324", "405"], "answerIndex": 1, "explanation": "ความสัมพันธ์คือคูณ 3 ไปเรื่อยๆ: 81 x 3 = 243" },
  { "id": 3, "category": "คณิตศาสตร์", "question": "ร้อยละ: ราคาสินค้า 2,500 บาท ลดราคา 15% จะต้องจ่ายเงินกี่บาท?", "options": ["2,125", "2,150", "2,200", "2,350"], "answerIndex": 0, "explanation": "ลด 15% คือจ่าย 85%; 2,500 x 0.85 = 2,125" },
  { "id": 4, "category": "คณิตศาสตร์", "question": "สมการ: 3(x - 4) = 15 ค่าของ x คือเท่าใด?", "options": ["5", "7", "9", "11"], "answerIndex": 2, "explanation": "x-4 = 15/3 -> x-4 = 5 -> x = 9" },
  { "id": 5, "category": "คณิตศาสตร์", "question": "ค่าเฉลี่ยของเลข 10, 20, 30, 40, 50 คือข้อใด?", "options": ["25", "30", "35", "40"], "answerIndex": 1, "explanation": "ผลรวม = 150; 150 / 5 = 30" },
  { "id": 6, "category": "คณิตศาสตร์", "question": "พื้นที่วงกลมที่มีรัศมี 7 ซม. มีค่าประมาณเท่าใด? (กำหนด π = 22/7)", "options": ["44", "154", "308", "616"], "answerIndex": 1, "explanation": "สูตร πr² = (22/7) x 7 x 7 = 154 ตร.ซม." },
  { "id": 7, "category": "คณิตศาสตร์", "question": "ถ้า 4x + 5 = 21 แล้ว x² มีค่าเท่าใด?", "options": ["4", "16", "25", "36"], "answerIndex": 1, "explanation": "4x = 16 -> x = 4; ดังนั้น x² = 16" },
  { "id": 8, "category": "คณิตศาสตร์", "question": "นกกับแมวรวมกันได้ 10 ตัว นับขารวมกันได้ 28 ขา มีแมวกี่ตัว?", "options": ["2", "4", "6", "8"], "answerIndex": 1, "explanation": "สมมติแมว x ตัว นก (10-x); 4x + 2(10-x) = 28 -> 2x = 8 -> x = 4" },
  { "id": 9, "category": "คณิตศาสตร์", "question": "ซื้อของมา 80 บาท ขายไป 100 บาท ได้กำไรกี่เปอร์เซ็นต์?", "options": ["20%", "25%", "30%", "40%"], "answerIndex": 1, "explanation": "กำไร 20 บาท; (20/80) x 100 = 25%" },
  { "id": 10, "category": "คณิตศาสตร์", "question": "15 คน ทำงานเสร็จใน 10 วัน ถ้าใช้ 5 คน จะเสร็จในกี่วัน?", "options": ["20", "25", "30", "50"], "answerIndex": 2, "explanation": "งานรวม = 15x10 = 150 แรงวัน; 150/5 = 30 วัน" },
  { "id": 11, "category": "คณิตศาสตร์", "question": "ห.ร.ม. ของ 12, 18 และ 24 คือข้อใด?", "options": ["2", "3", "6", "12"], "answerIndex": 2, "explanation": "เลขที่มากที่สุดที่หารทั้งสามตัวลงตัวคือ 6" },
  { "id": 12, "category": "คณิตศาสตร์", "question": "ค.ร.น. ของ 4, 6 และ 8 คือข้อใด?", "options": ["12", "24", "36", "48"], "answerIndex": 1, "explanation": "เลขที่น้อยที่สุดที่ทั้งสามตัวหารลงตัวคือ 24" },
  { "id": 13, "category": "คณิตศาสตร์", "question": "มุมภายในของรูปห้าเหลี่ยมรวมกันได้กี่องศา?", "options": ["360", "540", "720", "900"], "answerIndex": 1, "explanation": "สูตร (n-2) x 180 = (5-2) x 180 = 540" },
  { "id": 14, "category": "คณิตศาสตร์", "question": "อัตราส่วน: A:B = 2:3 และ B:C = 4:5 แล้ว A:B:C คือข้อใด?", "options": ["2:3:5", "8:12:15", "4:6:10", "8:10:15"], "answerIndex": 1, "explanation": "ทำให้ B เท่ากัน (3x4=12); A:B = 8:12, B:C = 12:15" },
  { "id": 15, "category": "คณิตศาสตร์", "question": "เลขสองจำนวนรวมกันได้ 50 ต่างกันอยู่ 10 เลขจำนวนมากคือข้อใด?", "options": ["25", "30", "35", "40"], "answerIndex": 1, "explanation": "x+y=50, x-y=10 -> 2x=60, x=30" },
  { "id": 16, "category": "คณิตศาสตร์", "question": "10! / 8! มีค่าเท่ากับข้อใด?", "options": ["2", "18", "80", "90"], "answerIndex": 3, "explanation": "10 x 9 x 8! / 8! = 10 x 9 = 90" },
  { "id": 17, "category": "คณิตศาสตร์", "question": "รถยนต์วิ่งด้วยความเร็ว 80 กม./ชม. ในเวลา 2.5 ชม. จะได้ระยะทางเท่าใด?", "options": ["160", "180", "200", "220"], "answerIndex": 2, "explanation": "ระยะทาง = ความเร็ว x เวลา = 80 x 2.5 = 200 กม." },
  { "id": 18, "category": "คณิตศาสตร์", "question": "ถ้า 2^x = 64 แล้ว x มีค่าเท่าใด?", "options": ["4", "5", "6", "7"], "answerIndex": 2, "explanation": "2 ยกกำลัง 6 ได้ 64" },
  { "id": 19, "category": "คณิตศาสตร์", "question": "ผลบวกของเลขคี่ตั้งแต่ 1 ถึง 19 คือข้อใด?", "options": ["81", "100", "121", "144"], "answerIndex": 1, "explanation": "จำนวนเทอม n=10; สูตร n² = 100" },
  { "id": 20, "category": "คณิตศาสตร์", "question": "รากที่สามของ 216 คือข้อใด?", "options": ["4", "6", "8", "12"], "answerIndex": 1, "explanation": "6 x 6 x 6 = 216" },
  { "id": 21, "category": "คณิตศาสตร์", "question": "ในถุงมีลูกบอลสีแดง 3 ลูก สีขาว 2 ลูก สุ่มหยิบ 1 ลูก ความน่าจะเป็นที่จะได้สีขาวคือ?", "options": ["1/5", "2/5", "3/5", "2/3"], "answerIndex": 1, "explanation": "2 ใน 5" },
  { "id": 22, "category": "คณิตศาสตร์", "question": "นาฬิกาเรือนหนึ่งราคา 1,200 บาท ติดป้ายลดราคาเหลือ 900 บาท ลดราคากี่เปอร์เซ็นต์?", "options": ["20%", "25%", "30%", "33%"], "answerIndex": 1, "explanation": "(300/1200) x 100 = 25%" },
  { "id": 23, "category": "คณิตศาสตร์", "question": "0, 3, 8, 15, 24, ... ตัวถัดไปคือ?", "options": ["30", "35", "40", "48"], "answerIndex": 1, "explanation": "เพิ่มเลขคี่ +3, +5, +7, +9, +11 (24+11=35)" },
  { "id": 24, "category": "คณิตศาสตร์", "question": "ค่าของ (2+3) x 4 - 5 คือเท่าใด?", "options": ["15", "17", "20", "25"], "answerIndex": 0, "explanation": "5 x 4 - 5 = 15" },
  { "id": 25, "category": "คณิตศาสตร์", "question": "รูปสี่เหลี่ยมจัตุรัสมีเส้นรอบรูปยาว 32 ซม. จะมีพื้นที่กี่ตารางซม.?", "options": ["16", "32", "64", "128"], "answerIndex": 2, "explanation": "ด้านยาว 8; 8x8=64" },
  { "id": 26, "category": "คณิตศาสตร์", "question": "ถ้า x:y = 3:4 และ x=15 แล้ว y มีค่าเท่าใด?", "options": ["16", "18", "20", "22"], "answerIndex": 2, "explanation": "15/y = 3/4 -> y=20" },
  { "id": 27, "category": "คณิตศาสตร์", "question": "เลข 5 จำนวนเรียงกัน ผลรวมคือ 100 เลขตรงกลางคือข้อใด?", "options": ["18", "19", "20", "21"], "answerIndex": 2, "explanation": "100/5 = 20" },
  { "id": 28, "category": "คณิตศาสตร์", "question": "ถังน้ำทรงสี่เหลี่ยมกว้าง 2ม. ยาว 3ม. สูง 1ม. จุน้ำได้กี่ลิตร?", "options": ["600", "1,000", "6,000", "60,000"], "answerIndex": 2, "explanation": "6 ลบ.ม. = 6,000 ลิตร" },
  { "id": 29, "category": "คณิตศาสตร์", "question": "ไซน์ 30 องศา (sin 30°) มีค่าเท่ากับเท่าใด?", "options": ["0", "1/2", "√3/2", "1"], "answerIndex": 1, "explanation": "ค่ามาตรฐานคือ 0.5" },
  { "id": 30, "category": "คณิตศาสตร์", "question": "ล็อกฐานสิบของ 100 (log10 100) มีค่าเท่าใด?", "options": ["1", "2", "10", "100"], "answerIndex": 1, "explanation": "10² = 100" },

  // --- หมวดที่ 2: ภาษาไทย [25 ข้อ: 31-55] ---
  { "id": 31, "category": "ภาษาไทย", "question": "ข้อใดคือคำพ้องรูป?", "options": ["กาล - การ", "เพลา (ตัก) - เพลา (เวลา)", "ซ่อม - ส้อม", "หน้า - น่า"], "answerIndex": 1, "explanation": "เขียนเหมือนแต่อ่านต่าง" },
  { "id": 32, "category": "ภาษาไทย", "question": "คำว่า 'ปรากฏ' ข้อใดเขียนถูกต้อง?", "options": ["ปรากฎ", "ปรากฏ", "ปรากต", "ปรากฎ์"], "answerIndex": 1, "explanation": "ใช้ ฏ (ตัก)" },
  { "id": 33, "category": "ภาษาไทย", "question": "สำนวน 'จับปลาสองมือ' หมายถึงข้อใด?", "options": ["ขยันทำงานหลายอย่าง", "ทำสองอย่างพร้อมกันจนไม่สำเร็จสักอย่าง", "มีความสามารถสูง", "หาปลาเก่ง"], "answerIndex": 1, "explanation": "มุ่งหวังสองอย่างพร้อมกันจนพลาดหมด" },
  { "id": 34, "category": "ภาษาไทย", "question": "ข้อใดเป็น 'ประโยคความเดียว'?", "options": ["ฉันกินข้าวและน้ำ", "น้องร้องไห้", "พ่อไปทำงานแต่แม่ทำงานบ้าน", "พี่อ่านหนังสือที่ซื้อมาใหม่"], "answerIndex": 1, "explanation": "ประโยคพื้นฐาน กริยาเดียว" },
  { "id": 35, "category": "ภาษาไทย", "question": "คำราชาศัพท์ 'เสวย' หมายถึงข้อใด?", "options": ["นอน", "เดิน", "กิน", "อาบน้ำ"], "answerIndex": 2, "explanation": "กิน" },
  { "id": 36, "category": "ภาษาไทย", "question": "ลักษณนามของ 'พระภิกษุ' คือข้อใด?", "options": ["คน", "องค์", "รูป", "ท่าน"], "answerIndex": 2, "explanation": "รูป" },
  { "id": 37, "category": "ภาษาไทย", "question": "คำในข้อใดเป็นคำสมาส?", "options": ["พลเมือง", "ราชการ", "ลูกชิ้น", "ไฟฟ้า"], "answerIndex": 1, "explanation": "ราชการ" },
  { "id": 38, "category": "ภาษาไทย", "question": "ข้อใดคือความหมายของ 'กระต่ายตื่นตูม'?", "options": ["คนขี้กลัว", "คนที่ตระหนกตกใจโดยไม่พิจารณาให้รอบคอบ", "คนหูไว", "คนวิ่งเร็ว"], "answerIndex": 1, "explanation": "ตื่นตกใจโดยไม่ดูสาเหตุ" },
  { "id": 39, "category": "ภาษาไทย", "question": "ข้อใดเขียนชื่อจังหวัดถูกต้อง?", "options": ["ศรสระเกษ", "ศรีสะเกษ", "สีสะเกษ", "ศรีสะเกศ"], "answerIndex": 1, "explanation": "ศรีสะเกษ" },
  { "id": 40, "category": "ภาษาไทย", "question": "คำตรงข้ามของ 'ประณีต' คือข้อใด?", "options": ["หยาบ", "เลว", "ง่าย", "เร็ว"], "answerIndex": 0, "explanation": "หยาบ" },
  { "id": 41, "category": "ภาษาไทย", "question": "ข้อใดเป็นคำนามสมุหนาม?", "options": ["ฝูงนก", "เด็กๆ", "โต๊ะ", "ความดี"], "answerIndex": 0, "explanation": "ฝูง" },
  { "id": 42, "category": "ภาษาไทย", "question": "คำแปลของ 'พระอัยกา' คือข้อใด?", "options": ["ย่า/ยาย", "ปู่/ตา", "พ่อ", "แม่"], "answerIndex": 1, "explanation": "ปู่/ตา" },
  { "id": 43, "category": "ภาษาไทย", "question": "ข้อใดสะกดถูกต้อง?", "options": ["กะเพรา", "กระเพรา", "กระเพา", "กะเพา"], "answerIndex": 0, "explanation": "กะเพรา" },
  { "id": 44, "category": "ภาษาไทย", "question": "ข้อความใดเป็นการเขียนแบบ 'บรรยายโวหาร'?", "options": ["ท้องฟ้าสีทองผ่องอำไพ", "เขาเดินออกจากบ้านไปในเวลาเช้าตรู่", "ความรักเหมือนโรคา", "ดอกไม้ค่อยๆ แย้มกลีบออก"], "answerIndex": 1, "explanation": "เล่าเรื่องตามลำดับ" },
  { "id": 45, "category": "ภาษาไทย", "question": "คำราชาศัพท์ 'พระที่นั่ง' หมายถึงข้อใดในบริบทของพาหนะ?", "options": ["เก้าอี้", "รถยนต์/เรือ", "เตียงนอน", "บ้าน"], "answerIndex": 1, "explanation": "รถ/เรือ" },
  { "id": 46, "category": "ภาษาไทย", "question": "คำว่า 'มงคล' มีความหมายตรงข้ามกับข้อใด?", "options": ["อัปมงคล", "เคราะห์", "กาลกิณี", "ถูกทุกข้อ"], "answerIndex": 3, "explanation": "สื่อทางร้ายทั้งหมด" },
  { "id": 47, "category": "ภาษาไทย", "question": "ข้อใดใช้คำราชาศัพท์กับ 'พระมหากษัตริย์' ได้ถูกต้อง?", "options": ["ทรงพระสรวล", "ทรงหัวเราะ", "ทรงยิ้ม", "ทรงรับประทาน"], "answerIndex": 0, "explanation": "ทรงพระสรวล" },
  { "id": 48, "category": "ภาษาไทย", "question": "คำนามในข้อใดเป็น 'อาการนาม'?", "options": ["การบ้าน", "การเมือง", "การเรียน", "การไฟฟ้า"], "answerIndex": 2, "explanation": "การเรียน" },
  { "id": 49, "category": "ภาษาไทย", "question": "จดหมายลาป่วยควรใช้คำลงท้ายว่าอย่างไร?", "options": ["ด้วยความเคารพ", "ขอแสดงความนับถือ", "ด้วยความเคารพอย่างสูง", "จึงเรียนมาเพื่อทราบ"], "answerIndex": 2, "explanation": "เคารพอย่างสูง" },
  { "id": 50, "category": "ภาษาไทย", "question": "ข้อใดใช้เครื่องหมาย 'อัญประกาศ' ได้ถูกต้อง?", "options": ["ใช้เน้นคำ", "ใช้ครอบข้อความที่เป็นคำพูด", "ใช้จบประโยค", "ใช้ละข้อความ"], "answerIndex": 1, "explanation": "เครื่องหมายคำพูด" },
  { "id": 51, "category": "ภาษาไทย", "question": "คำว่า 'พิจารณา' อ่านว่าอย่างไร?", "options": ["พิจ-จา-ระ-นา", "พิจ-รา-นา", "พิ-จา-ระ-นา", "พิ-จา-นา"], "answerIndex": 2, "explanation": "พิ-จา-ระ-นา" },
  { "id": 52, "category": "ภาษาไทย", "question": "สำนวนใดหมายถึง 'การเริ่มต้นทำอะไรสักอย่าง'?", "options": ["นับหนึ่งใหม่", "ตักน้ำรดหัวตอ", "เขียนเสือให้วัวกลัว", "ลงเรือลำเดียวกัน"], "answerIndex": 0, "explanation": "เริ่มใหม่" },
  { "id": 53, "category": "ภาษาไทย", "question": "คำว่า 'กาลเทศะ' หมายถึงข้อใด?", "options": ["เวลา", "สถานที่", "ความเหมาะสมของเวลาและสถานที่", "กฎระเบียบ"], "answerIndex": 2, "explanation": "เวลาและสถานที่" },
  { "id": 54, "category": "ภาษาไทย", "question": "ข้อใดเป็นคำที่มาจากภาษาเขมร?", "options": ["บิดา", "ถนน", "กาแฟ", "คอมพิวเตอร์"], "answerIndex": 1, "explanation": "ถนน" },
  { "id": 55, "category": "ภาษาไทย", "question": "คำในข้อใดใช้ 'ไม้ยมก' ได้ถูกต้อง?", "options": ["จะจะ", "ที่หนึ่งๆ", "คนๆ หนึ่ง", "ไปๆ มาๆ"], "answerIndex": 3, "explanation": "ไปๆ มาๆ" },

  // --- หมวดที่ 3: ภาษาอังกฤษ [30 ข้อ: 56-85] ---
  { "id": 56, "category": "ภาษาอังกฤษ", "question": "He ______ to school every day.", "options": ["go", "goes", "going", "gone"], "answerIndex": 1, "explanation": "Present Simple" },
  { "id": 57, "category": "ภาษาอังกฤษ", "question": "Plural form of 'Child'?", "options": ["Childs", "Children", "Childrens", "Childes"], "answerIndex": 1, "explanation": "Children" },
  { "id": 58, "category": "ภาษาอังกฤษ", "question": "I ______ a teacher since 2010.", "options": ["am", "was", "have been", "had"], "answerIndex": 2, "explanation": "Present Perfect with 'since'" },
  { "id": 59, "category": "ภาษาอังกฤษ", "question": "The meeting ______ at 9:00 AM.", "options": ["start", "starts", "starting", "started"], "answerIndex": 1, "explanation": "Timetable" },
  { "id": 60, "category": "ภาษาอังกฤษ", "question": "Which word is an adjective?", "options": ["Quickly", "Happiness", "Beautiful", "Run"], "answerIndex": 2, "explanation": "Beautiful" },
  { "id": 61, "category": "ภาษาอังกฤษ", "question": "I'm looking forward to ______ you.", "options": ["see", "saw", "seen", "seeing"], "answerIndex": 3, "explanation": "look forward to + V-ing" },
  { "id": 62, "category": "ภาษาอังกฤษ", "question": "If I ______ you, I would go.", "options": ["am", "was", "were", "be"], "answerIndex": 2, "explanation": "Type 2 conditional" },
  { "id": 63, "category": "ภาษาอังกฤษ", "question": "Could you ______ me the salt?", "options": ["pass", "past", "passed", "passing"], "answerIndex": 0, "explanation": "Infinitive" },
  { "id": 64, "category": "ภาษาอังกฤษ", "question": "She is ______ than her sister.", "options": ["tall", "taller", "tallest", "more tall"], "answerIndex": 1, "explanation": "Comparative" },
  { "id": 65, "category": "ภาษาอังกฤษ", "question": "Don't forget to ______ the lights.", "options": ["turn on", "turn off", "turn up", "turn down"], "answerIndex": 1, "explanation": "Turn off" },
  { "id": 66, "category": "ภาษาอังกฤษ", "question": "Synonym of 'Happy'?", "options": ["Sad", "Angry", "Joyful", "Bored"], "answerIndex": 2, "explanation": "Joyful" },
  { "id": 67, "category": "ภาษาอังกฤษ", "question": "Where ______ you go last night?", "options": ["do", "does", "did", "done"], "answerIndex": 2, "explanation": "Past tense question" },
  { "id": 68, "category": "ภาษาอังกฤษ", "question": "The man ______ car was stolen.", "options": ["who", "whom", "whose", "which"], "answerIndex": 2, "explanation": "Whose (possession)" },
  { "id": 69, "category": "ภาษาอังกฤษ", "question": "Please ______ the document.", "options": ["send", "sends", "sending", "sent"], "answerIndex": 0, "explanation": "Command" },
  { "id": 70, "category": "ภาษาอังกฤษ", "question": "Interested ______ learning.", "options": ["on", "at", "in", "with"], "answerIndex": 2, "explanation": "Interested in" },
  { "id": 71, "category": "ภาษาอังกฤษ", "question": "What ______ you doing?", "options": ["are", "was", "were", "been"], "answerIndex": 2, "explanation": "Were + V-ing" },
  { "id": 72, "category": "ภาษาอังกฤษ", "question": "Between the bank ______ the post office.", "options": ["to", "or", "and", "but"], "answerIndex": 2, "explanation": "Between...and..." },
  { "id": 73, "category": "ภาษาอังกฤษ", "question": "He has ______ money.", "options": ["few", "little", "many", "much"], "answerIndex": 1, "explanation": "Little (uncountable/negative)" },
  { "id": 74, "category": "ภาษาอังกฤษ", "question": "You ______ smoke in here.", "options": ["must", "mustn't", "should", "can"], "answerIndex": 1, "explanation": "Prohibition" },
  { "id": 75, "category": "ภาษาอังกฤษ", "question": "Which one is a fruit?", "options": ["Cabbage", "Carrot", "Cherry", "Cucumber"], "answerIndex": 2, "explanation": "Cherry" },
  { "id": 76, "category": "ภาษาอังกฤษ", "question": "How to ______ to the station?", "options": ["go", "get", "make", "be"], "answerIndex": 1, "explanation": "Get to" },
  { "id": 77, "category": "ภาษาอังกฤษ", "question": "She ______ English well.", "options": ["speak", "speaks", "speaking", "spoken"], "answerIndex": 1, "explanation": "Speaks" },
  { "id": 78, "category": "ภาษาอังกฤษ", "question": "We have ______ time.", "options": ["a lot of", "much", "limited", "no"], "answerIndex": 2, "explanation": "Limited (context)" },
  { "id": 79, "category": "ภาษาอังกฤษ", "question": "On the table.", "options": ["in", "on", "at", "by"], "answerIndex": 1, "explanation": "On" },
  { "id": 80, "category": "ภาษาอังกฤษ", "question": "It is ______ (mine).", "options": ["my", "mine", "me", "I"], "answerIndex": 1, "explanation": "Possessive pronoun" },
  { "id": 81, "category": "ภาษาอังกฤษ", "question": "Yesterday they ______ dinner.", "options": ["eat", "ate", "eaten", "eats"], "answerIndex": 1, "explanation": "Ate" },
  { "id": 82, "category": "ภาษาอังกฤษ", "question": "Correct spelling?", "options": ["Recieve", "Receive", "Receve", "Reseive"], "answerIndex": 1, "explanation": "Receive" },
  { "id": 83, "category": "ภาษาอังกฤษ", "question": "Would you mind ______?", "options": ["open", "opens", "opened", "opening"], "answerIndex": 3, "explanation": "Opening" },
  { "id": 84, "category": "ภาษาอังกฤษ", "question": "Depend ______.", "options": ["on", "at", "in", "to"], "answerIndex": 0, "explanation": "Depend on" },
  { "id": 85, "category": "ภาษาอังกฤษ", "question": "Opposite of 'Difficult'?", "options": ["Hard", "Easy", "Complex", "Slow"], "answerIndex": 1, "explanation": "Easy" },

  // --- หมวดที่ 4: คอมพิวเตอร์/IT (สำนักงาน) [25 ข้อ: 86-110] ---
  { "id": 86, "category": "คอมพิวเตอร์/IT", "question": "โปรแกรมใดเหมาะสำหรับการจัดทำเอกสารรายงาน?", "options": ["MS Excel", "MS Word", "MS PowerPoint", "MS Access"], "answerIndex": 1, "explanation": "MS Word" },
  { "id": 87, "category": "คอมพิวเตอร์/IT", "question": "Ctrl + S คือ?", "options": ["Copy", "Paste", "Save", "Print"], "answerIndex": 2, "explanation": "Save" },
  { "id": 88, "category": "คอมพิวเตอร์/IT", "question": "นามสกุลไฟล์ .xlsx คือ?", "options": ["Word", "Excel", "PowerPoint", "Outlook"], "answerIndex": 1, "explanation": "Excel" },
  { "id": 89, "category": "คอมพิวเตอร์/IT", "question": "ตารางคำนวณควรใช้?", "options": ["Word", "Excel", "Notepad", "Paint"], "answerIndex": 1, "explanation": "Excel" },
  { "id": 90, "category": "คอมพิวเตอร์/IT", "question": "ปุ่ม F5 ใน PowerPoint คือ?", "options": ["Save", "New", "Slide Show", "Exit"], "answerIndex": 2, "explanation": "เริ่มนำเสนอ" },
  { "id": 91, "category": "คอมพิวเตอร์/IT", "question": "หน่วยความเร็วอินเทอร์เน็ต?", "options": ["GB", "Mbps", "MHz", "DPI"], "answerIndex": 1, "explanation": "Mbps" },
  { "id": 92, "category": "คอมพิวเตอร์/IT", "question": "Input Unit คือ?", "options": ["Monitor", "Printer", "Keyboard", "Speaker"], "answerIndex": 2, "explanation": "Keyboard" },
  { "id": 93, "category": "คอมพิวเตอร์/IT", "question": "RAM ย่อมาจาก?", "options": ["Read Access Memory", "Random Access Memory", "Real Action Memory", "Rapid Access Memory"], "answerIndex": 1, "explanation": "Random Access Memory" },
  { "id": 94, "category": "คอมพิวเตอร์/IT", "question": "Copy + Paste?", "options": ["Ctrl+C, Ctrl+V", "Ctrl+X, Ctrl+V", "Ctrl+C, Ctrl+P", "Ctrl+S, Ctrl+O"], "answerIndex": 0, "explanation": "C และ V" },
  { "id": 95, "category": "คอมพิวเตอร์/IT", "question": "OS ยอดนิยมในสำนักงาน?", "options": ["Android", "iOS", "Windows", "Linux"], "answerIndex": 2, "explanation": "Windows" },
  { "id": 96, "category": "คอมพิวเตอร์/IT", "question": "ช่องใน Excel เรียกว่า?", "options": ["Box", "Cell", "Table", "Sheet"], "answerIndex": 1, "explanation": "Cell" },
  { "id": 97, "category": "คอมพิวเตอร์/IT", "question": "Browser ใช้สำหรับ?", "options": ["Coding", "Design", "Internet Surfing", "Music"], "answerIndex": 2, "explanation": "เข้าเว็บ" },
  { "id": 98, "category": "คอมพิวเตอร์/IT", "question": "ส่งสำเนาลับอีเมล?", "options": ["To", "CC", "BCC", "Subject"], "answerIndex": 2, "explanation": "BCC" },
  { "id": 99, "category": "คอมพิวเตอร์/IT", "question": "เสี่ยงไวรัสที่สุด?", "options": ["Update Windows", "Strong Pass", "Clicking Unknown Links", "Antivirus Scan"], "answerIndex": 2, "explanation": "คลิกลิงก์แปลก" },
  { "id": 100, "category": "คอมพิวเตอร์/IT", "question": "PrtSc บนคีย์บอร์ดคือ?", "options": ["Print", "Screen Capture", "Screen Off", "Delete"], "answerIndex": 1, "explanation": "จับภาพหน้าจอ" },
  { "id": 101, "category": "คอมพิวเตอร์/IT", "question": "เปลี่ยน Font ใน Word?", "options": ["Insert", "Home", "Layout", "View"], "answerIndex": 1, "explanation": "Home" },
  { "id": 102, "category": "คอมพิวเตอร์/IT", "question": "=IF() ใน Excel คือ?", "options": ["Sum", "Average", "Condition", "Count"], "answerIndex": 2, "explanation": "เงื่อนไข" },
  { "id": 103, "category": "คอมพิวเตอร์/IT", "question": "Multitasking คือ?", "options": ["Multi-user", "Multi-program", "Multi-connection", "Fast typing"], "answerIndex": 1, "explanation": "ทำหลายงานพร้อมกัน" },
  { "id": 104, "category": "คอมพิวเตอร์/IT", "question": "นามสกุลไฟล์รูปขนาดเล็ก?", "options": [".exe", ".jpg", ".txt", ".wav"], "answerIndex": 1, "explanation": "JPG" },
  { "id": 105, "category": "คอมพิวเตอร์/IT", "question": "ผิด พ.ร.บ.คอมพิวเตอร์?", "options": ["Cyberbullying", "Hacking", "Malware spreading", "All of above"], "answerIndex": 3, "explanation": "ทุกข้อ" },
  { "id": 106, "category": "คอมพิวเตอร์/IT", "question": "สมองคอมพิวเตอร์?", "options": ["Monitor", "CPU", "Hard Disk", "Power Supply"], "answerIndex": 1, "explanation": "CPU" },
  { "id": 107, "category": "คอมพิวเตอร์/IT", "question": "ข้อดี Google Docs?", "options": ["No Net", "Save to Disk", "Real-time Collaboration", "No Virus"], "answerIndex": 2, "explanation": "ทำงานร่วมกัน" },
  { "id": 108, "category": "คอมพิวเตอร์/IT", "question": "Ctrl + P คือ?", "options": ["Paste", "Print", "New", "Center"], "answerIndex": 1, "explanation": "Print" },
  { "id": 109, "category": "คอมพิวเตอร์/IT", "question": "Wi-Fi คือ?", "options": ["Wireless Printing", "Wireless Internet", "Graphics", "Backup"], "answerIndex": 1, "explanation": "เน็ตไร้สาย" },
  { "id": 110, "category": "คอมพิวเตอร์/IT", "question": "Password ที่ดี?", "options": ["Phone No.", "Birthday", "Mix of letters/numbers", "123456"], "answerIndex": 2, "explanation": "ตัวเลขผสมตัวอักษร" },

  // --- หมวดที่ 5: กฎหมายที่ประชาชนควรรู้ [20 ข้อ: 111-130] ---
  { "id": 111, "category": "กฎหมาย", "question": "บรรลุนิติภาวะเมื่ออายุ?", "options": ["15", "17", "18", "20"], "answerIndex": 3, "explanation": "20 ปี" },
  { "id": 112, "category": "กฎหมาย", "question": "ทำบัตรประชาชนครั้งแรกเมื่ออายุ?", "options": ["7", "10", "12", "15"], "answerIndex": 0, "explanation": "7 ปี" },
  { "id": 113, "category": "กฎหมาย", "question": "หมั้นได้เมื่ออายุ?", "options": ["15", "17", "18", "20"], "answerIndex": 1, "explanation": "17 ปี" },
  { "id": 114, "category": "กฎหมาย", "question": "กฎหมายสูงสุดคือ?", "options": ["Police Act", "Criminal Law", "Constitution", "Civil Law"], "answerIndex": 2, "explanation": "รัฐธรรมนูญ" },
  { "id": 115, "category": "กฎหมาย", "question": "แจ้งเกิดภายใน?", "options": ["24 ชม.", "7 วัน", "15 วัน", "30 วัน"], "answerIndex": 2, "explanation": "15 วัน" },
  { "id": 116, "category": "กฎหมาย", "question": "แจ้งตายภายใน?", "options": ["12 ชม.", "24 ชม.", "48 ชม.", "72 ชม."], "answerIndex": 1, "explanation": "24 ชม." },
  { "id": 117, "category": "กฎหมาย", "question": "คนไร้ความสามารถอยู่ในความดูแลของ?", "options": ["ผู้อนุบาล", "ผู้พิทักษ์", "ผู้แทน", "พ่อแม่"], "answerIndex": 0, "explanation": "ผู้อนุบาล" },
  { "id": 118, "category": "กฎหมาย", "question": "พินัยกรรมเขียนเองต้องมีพยาน?", "options": ["0", "1", "2", "3"], "answerIndex": 0, "explanation": "0 (ถ้าเขียนเองหมด)" },
  { "id": 119, "category": "กฎหมาย", "question": "โทษอาญาสูงสุด?", "options": ["กักขัง", "ปรับ", "ตลอดชีวิต", "ประหาร"], "answerIndex": 3, "explanation": "ประหาร" },
  { "id": 120, "category": "กฎหมาย", "question": "แจ้งย้ายออกภายใน?", "options": ["7", "15", "30", "60"], "answerIndex": 1, "explanation": "15 วัน" },
  { "id": 121, "category": "กฎหมาย", "question": "ลักทรัพย์คือ?", "options": ["แย่งซึ่งหน้า", "เอาไปทุจริต", "บังคับเอา", "3 คนขึ้นไป"], "answerIndex": 1, "explanation": "แอบเอาไป" },
  { "id": 122, "category": "กฎหมาย", "question": "กู้เงินเกิน 2,000 ต้องมี?", "options": ["พยานบุคคล", "รูปถ่าย", "หนังสือลงชื่อผู้กู้", "วิดีโอ"], "answerIndex": 2, "explanation": "หลักฐานหนังสือ" },
  { "id": 123, "category": "กฎหมาย", "question": "ป้องกันตัวโดยชอบ?", "options": ["ยิงคนหนี", "ตีหมาจะกัด", "ป้องกันภัยใกล้ถึงไม่เกินเหตุ", "จ้างคนตีคืน"], "answerIndex": 2, "explanation": "พอสมควรแก่เหตุ" },
  { "id": 124, "category": "กฎหมาย", "question": "อสังหาริมทรัพย์?", "options": ["Car", "Gold", "Land", "Dog"], "answerIndex": 2, "explanation": "ที่ดิน" },
  { "id": 125, "category": "กฎหมาย", "question": "อายุความฆ่าคนเจตนา?", "options": ["10", "15", "20", "30"], "answerIndex": 2, "explanation": "20 ปี" },
  { "id": 126, "category": "กฎหมาย", "question": "เก็บของตกได้แล้วเอาไปเลย?", "options": ["ลักทรัพย์", "ยักยอกทรัพย์สินหาย", "ชิงทรัพย์", "ไม่ผิด"], "answerIndex": 1, "explanation": "ยักยอกทรัพย์สินหาย" },
  { "id": 127, "category": "กฎหมาย", "question": "สมรสสมบูรณ์เมื่อ?", "options": ["จัดงาน", "อยู่กิน 1 ปี", "จดทะเบียน", "พ่อแม่รู้"], "answerIndex": 2, "explanation": "จดทะเบียน" },
  { "id": 128, "category": "กฎหมาย", "question": "เช็คเด้ง?", "options": ["Civil", "Criminal (Compounded)", "Criminal (Non-Compounded)", "No case"], "answerIndex": 1, "explanation": "อาญา ยอมความได้" },
  { "id": 129, "category": "กฎหมาย", "question": "มรดกตกทอดเมื่อ?", "options": ["ตาย", "ทำพินัยกรรม", "อายุ 60", "ทายาทขอ"], "answerIndex": 0, "explanation": "ตาย" },
  { "id": 130, "category": "กฎหมาย", "question": "ทายาทลำดับ 1?", "options": ["Siblings", "Grandparents", "Spouse", "Descendants"], "answerIndex": 3, "explanation": "ผู้สืบสันดาน" },

  // --- หมวดที่ 6: สังคม/จริยธรรม/อาเซียน [20 ข้อ: 131-150] ---
  { "id": 131, "category": "สังคม/อาเซียน", "question": "อาเซียนก่อตั้งที่?", "options": ["Indonesia", "Singapore", "Thailand", "Philippines"], "answerIndex": 2, "explanation": "ไทย" },
  { "id": 132, "category": "สังคม/อาเซียน", "question": "เลขาธิการอาเซียนอยู่ที่?", "options": ["Bangkok", "Jakarta", "KL", "Manila"], "answerIndex": 1, "explanation": "จาการ์ตา" },
  { "id": 133, "category": "สังคม/อาเซียน", "question": "สมาชิกคนที่ 10?", "options": ["Vietnam", "Myanmar", "Laos", "Cambodia"], "answerIndex": 3, "explanation": "กัมพูชา" },
  { "id": 134, "category": "สังคม/อาเซียน", "question": "คำขวัญอาเซียน?", "options": ["One Vision...", "Unity...", "Progress...", "Peace..."], "answerIndex": 0, "explanation": "หนึ่งวิสัยทัศน์..." },
  { "id": 135, "category": "สังคม/อาเซียน", "question": "เสาหลักอาเซียน?", "options": ["Politics", "Economy", "Socio-Cultural", "All"], "answerIndex": 3, "explanation": "3 เสา" },
  { "id": 136, "category": "สังคม/จริยธรรม", "question": "ความอดทนคือ?", "options": ["ขันติ", "โสรัจจะ", "เมตตา", "สัจจะ"], "answerIndex": 0, "explanation": "ขันติ" },
  { "id": 137, "category": "สังคม/จริยธรรม", "question": "ยินดีเมื่อผู้อื่นได้ดี?", "options": ["เมตตา", "กรุณา", "มุทิตา", "อุเบกขา"], "answerIndex": 2, "explanation": "มุทิตา" },
  { "id": 138, "category": "สังคม/จริยธรรม", "question": "ศีลข้อ 4?", "options": ["ลักทรัพย์", "ผิดกาม", "มุสา", "สุรา"], "answerIndex": 2, "explanation": "โกหก" },
  { "id": 139, "category": "สังคม/อาเซียน", "question": "เพลงอาเซียน?", "options": ["ASEAN Soul", "The ASEAN Way", "ASEAN Spirit", "Power of Ten"], "answerIndex": 1, "explanation": "The ASEAN Way" },
  { "id": 140, "category": "สังคม/อาเซียน", "question": "สีน้ำเงินในธงอาเซียน?", "options": ["Brave", "Purity", "Peace/Stability", "Prosperity"], "answerIndex": 2, "explanation": "สันติภาพ" },
  { "id": 141, "category": "สังคม/จริยธรรม", "question": "มาฆบูชาเดือน?", "options": ["3", "6", "8", "12"], "answerIndex": 0, "explanation": "เดือน 3" },
  { "id": 142, "category": "สังคม/จริยธรรม", "question": "อาคเนย์คือ?", "options": ["SW", "NE", "SE", "NW"], "answerIndex": 2, "explanation": "SE" },
  { "id": 143, "category": "สังคม/จริยธรรม", "question": "เวียนเทียนระลึกถึง?", "options": ["King", "Triple Gem", "Ancestors", "Angels"], "answerIndex": 1, "explanation": "พระรัตนตรัย" },
  { "id": 144, "category": "สังคม/อาเซียน", "question": "เงินมาเลเซีย?", "options": ["Baht", "Dollar", "Ringgit", "Kyat"], "answerIndex": 2, "explanation": "ริงกิต" },
  { "id": 145, "category": "สังคม/อาเซียน", "question": "ดอกไม้ไทย?", "options": ["Rose", "Jasmine", "Ratchaphruek", "Orchid"], "answerIndex": 2, "explanation": "ราชพฤกษ์" },
  { "id": 146, "category": "สังคม/จริยธรรม", "question": "วัฒนธรรมทางวัตถุ?", "options": ["Etiquette", "Songkran", "Temples", "Gratitude"], "answerIndex": 2, "explanation": "วัด" },
  { "id": 147, "category": "สังคม/จริยธรรม", "question": "ค่านิยมข้อ 1?", "options": ["Gratitude", "Culture", "Nation/Religion/King", "Honesty"], "answerIndex": 2, "explanation": "ชาติ ศาสนา กษัตริย์" },
  { "id": 148, "category": "สังคม/จริยธรรม", "question": "ไหว้พระสงฆ์?", "options": ["Chest", "Chin", "Eyebrows", "Forehead"], "answerIndex": 2, "explanation": "ระหว่างคิ้ว" },
  { "id": 149, "category": "สังคม/จริยธรรม", "question": "พอเพียงมีกี่ห่วง?", "options": ["1", "2", "3", "4"], "answerIndex": 2, "explanation": "3 ห่วง" },
  { "id": 150, "category": "สังคม/จริยธรรม", "question": "วันรัฐธรรมนูญ?", "options": ["5 Dec", "10 Dec", "12 Aug", "24 June"], "answerIndex": 1, "explanation": "10 ธันวาคม" }
];
